### ISSUE TITLE
EEXIST: file already exists

### ISSUE THREAD

**Issue by GCorbel** [toranb/ember-cli-hot-loader#29]
When I work with glimmer 2, I have this error : 
```
Error: EEXIST: file already exists, symlink '/frontend/app/pods/components/flight-form/component.js' -> '/frontend/tmp/broccoli_merge_trees-output_path-6aN7L0OY.tmp/log-book/pods/components/flight-form/component.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at FSMonitor._measure (/frontend/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.symlinkSync (/frontend/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at symlink (/frontend/node_modules/symlink-or-copy/index.js:79:14)
    at symlinkOrCopySync (/frontend/node_modules/symlink-or-copy/index.js:55:5)
    at BroccoliMergeTrees.<anonymous> (/frontend/node_modules/broccoli-merge-trees/index.js:137:16)
    at Array.forEach (native)
    at BroccoliMergeTrees._applyPatch (/frontend/node_modules/broccoli-merge-trees/index.js:114:9)
    at BroccoliMergeTrees.build (/frontend/node_modules/broccoli-merge-trees/index.js:101:10)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/frontend/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/frontend/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/frontend/node_modules/broccoli-merge-trees/index.js:36:53)
    at module.exports (/frontend/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp.appAndDependencies (/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1079:44)
    at EmberApp.javascript (/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1217:34)
    at EmberApp.toArray (/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1646:10)
    at EmberApp.toTree (/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1668:30)
    at module.exports (/frontend/ember-cli-build.js:60:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/frontend/node_modules/ember-cli/lib/models/builder.js:70:19)
```

It works the first 4 or 5 times but it fail just after.

**Comment by GCorbel** [comment]
I'm working on Ember 2.10.beta-3 with Glimmer 2

**Comment by GCorbel** [comment]
I think this is not really related to ember-cli-hot-loader. I will open an issue in the Broccoli's Github and close this one.

**Comment by toranb** [comment]
@GCorbel I was going to ask if this occurs when you save a single file (solo) or if you are indeed saving a group of files at once?

**Comment by GCorbel** [comment]
I happens but less frequently.
