### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by vlascik** [toranb/ember-cli-hot-loader#36]
I'm getting a following error:
```
"TypeError: Cannot convert undefined or null to object"
"    at Function.keys (<anonymous>)"
"    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:264072:34)"
"    at TopComponentManager.templateFor (http://localhost:4200/assets/vendor.js:38320:34)"
"    at TopComponentManager.layoutFor (http://localhost:4200/assets/vendor.js:38314:25)"
"    at OpenComponentOpcode.evaluate (http://localhost:4200/assets/vendor.js:73033:34)"
"    at VM.execute (http://localhost:4200/assets/vendor.js:79506:28)"
"    at RootState.render (http://localhost:4200/assets/vendor.js:37557:46)"
"    at runInTransaction (http://localhost:4200/assets/vendor.js:48520:28)"
"    at InteractiveRenderer._renderRoots (http://localhost:4200/assets/vendor.js:37822:48)"
"    at InteractiveRenderer._renderRootsTransaction (http://localhost:4200/assets/vendor.js:37860:14)"
```
the offending line is in `layout()` function of `HotReplacementComponent`
`var attributesMap = Object.keys(this.attrs).filter(function (key) {`

ember-cli-hot-loader: 0.1.3
ember: 2.10.0-beta.3
ember-cli: 2.10.0-beta.2
node: 6.7.0
os: win32 x64

**Comment by PTC-JoshuaMatthews** [comment]
Any solution for this?

**Comment by toranb** [comment]
Can you reproduce this for us so we can find the root cause?

**Comment by ianpetzer** [comment]
@vlascik @PTC-JoshuaMatthews Did you every have any success with this? I'm running into the same issue
