### ISSUE TITLE
Cant start ember server

### ISSUE THREAD

**Issue by fidlip** [toranb/ember-cli-hot-loader#58]
After successful install I tried to run "ember s", this is the result:
```
Cannot find module 'ember-source/dist/ember-template-compiler.js'
Error: Cannot find module 'ember-source/dist/ember-template-compiler.js'
  at Function.Module._resolveFilename (module.js:470:15)
  at Function.resolve (internal/module.js:27:19)
  at Class.included (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/ember-cli-hot-loader/index.js:25:31)
  at Class.superWrapper [as included] (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/core-object/lib/assign-properties.js:32:18)
  at EmberApp.<anonymous> (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:469:15)
  at Array.filter (native)
  at EmberApp._notifyAddonIncluded (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:464:45)
  at new EmberApp (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/ember-cli/lib/broccoli/ember-app.js:137:8)
  at module.exports (/home/fidlip/dev/wspace/rls/dashboard-ui/ember-cli-build.js:41:13)
  at Class.setupBroccoliBuilder (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/ember-cli/lib/models/builder.js:72:19)
  at Class.init (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/ember-cli/lib/models/builder.js:52:10)
  at Class.superWrapper [as init] (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/core-object/lib/assign-properties.js:32:18)
  at Class (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/core-object/core-object.js:32:33)
  at Class.run (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/ember-cli/lib/tasks/serve.js:15:19)
  at /home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/ember-cli/lib/commands/serve.js:76:24
  at tryCatch (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/rsvp/dist/rsvp.js:525:12)
  at invokeCallback (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/rsvp/dist/rsvp.js:538:13)
  at /home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/rsvp/dist/rsvp.js:606:14
  at flush (/home/fidlip/dev/wspace/rls/dashboard-ui/node_modules/rsvp/dist/rsvp.js:2415:5)
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)


npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/home/fidlip/.nvm/versions/node/v7.10.0/bin/node" "/home/fidlip/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/npm-cli.js" "run" "start" "--scripts-prepend-node-path=auto"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dashboard@0.0.1 start: `ember server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dashboard@0.0.1 start script 'ember server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fidlip/.npm/_logs/2018-03-13T17_22_51_986Z-debug.log

Process finished with exit code 1

```
ember: 2.11.2
node: 7.10.0

**Comment by fidlip** [comment]
It was due to bower installed ember. Changed to npm installed ember-sources and this error dismissed. Closing this issue.
